# Esta linha especifica a versão do Docker Compose file format que está sendo usada.
version: "3.8"

# Esta seção define os serviços que serão usados no aplicativo.
#
# Cada serviço é uma imagem Docker que será iniciada como um contêiner.
services:
  # Este é o nome do primeiro serviço, que será usado para executar o servidor NGINX.
  server:
    # Esta linha especifica a imagem Docker que será usada para iniciar o serviço.
    #
    # Neste caso, é a imagem oficial do Nginx usando o Alpine Linux como base.
    #
    # A imagem Alpine é uma imagem de sistema operacional pequena e minimalista baseada em Linux,
    # o que a torna uma boa opção para usar como imagem base em contêineres Docker devido ao seu tamanho pequeno.
    image: nginx:alpine

    # Esta seção define as portas que serão expostas para o host.
    #
    # O formato é "host:container", então neste caso, a porta 9000 do host será mapeada para a porta 80 do contêiner.
    # Ou sejá, requisições HTTP para a porta 9000 (http://example.com:9000/) seram direcionadas para a porta 80 do contêiner.
    ports:
      - "9000:80"

    # Esta seção define os volumes que serão montados no contêiner.
    #
    # Os volumes permitem que você compartilhe arquivos entre o host e o contêiner.
    # Neste caso, o arquivo "nginx.conf" do host será montado no diretório "/etc/nginx/nginx.conf" do contêiner
    # e a pasta "build" do host será montada no diretório "/usr/share/nginx/html" do contêiner.
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./build:/usr/share/nginx/html

  # Este é o nome do segundo serviço, que será usado para construir e executar a aplicação React.
  app:
    # Esta seção define as configurações de construção para o serviço.
    #
    # O "context" especifica o diretório base que será usado para procurar o Dockerfile.
    # O "dockerfile" especifica o caminho relativo para o Dockerfile em questão.
    build:
      context: .
      dockerfile: Dockerfile

    # Esta seção define um volume adicional que será montado no contêiner.
    #
    # Neste caso, a pasta "app" do host será montada no diretório "/app" do contêiner.
    volumes:
      - ./app:/app