version: "3.8"
services:
  app:
    image: node:14
    ports:
      - "9000:80"
    command: bash -c "npm install && npm run build && nginx -g 'daemon off;'"
    volumes:
      - ./:/app
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./build:/usr/share/nginx/html
    depends_on:
      - app